-- 코드를 입력하세요
SELECT CONCAT('/home/grep/src/', UF.BOARD_ID, '/', FILE_ID, FILE_NAME, FILE_EXT) AS FILE_PATH
    FROM USED_GOODS_BOARD AS UB JOIN USED_GOODS_FILE AS UF
    ON UB.BOARD_ID = UF.BOARD_ID
    WHERE UB.VIEWS = (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD)
    ORDER BY FILE_ID DESC